drop table ABOUTME cascade constraints;
drop table ADDRESS cascade constraints;
drop table APPEARANCE cascade constraints;
drop table APPEARANCE_APPEARANCESTYLES cascade constraints;
drop table CITY cascade constraints;
drop table CONTACTEVENT cascade constraints;
drop table CREDITCARDACCOUNT cascade constraints;
drop table FAVORITE cascade constraints;
drop table GEOLOCATION cascade constraints;
drop table IMAGEENTRY cascade constraints;
drop table LANDINGPAGEACTION cascade constraints;
drop table LIFESTYLE cascade constraints;
drop table LIFESTYLE_FOODTYPES cascade constraints;
drop table LIFESTYLE_HOBBYTYPES cascade constraints;
drop table LIFESTYLE_HOLIDAYTYPES cascade constraints;
drop table LIFESTYLE_KITCHENTYPES cascade constraints;
drop table LIFESTYLE_MUSICTYPES cascade constraints;
drop table LIFESTYLE_PETTYPES cascade constraints;
drop table LIFESTYLE_SPORTTYPES cascade constraints;
drop table MEMBERSHIP cascade constraints;
drop table MESSAGE cascade constraints;
drop table PAYMENTCHANNEL cascade constraints;
drop table PAYPALACCOUNT cascade constraints;
drop table SEARCHPROFILE cascade constraints;
drop table SEARCHPROFILE_APPEARANCESTYLES cascade constraints;
drop table SEARCHPROFILE_BODYTYPES cascade constraints;
drop table SEARCHPROFILE_EDUCATIONTYPES cascade constraints;
drop table SEARCHPROFILE_ETHNICITIES cascade constraints;
drop table SEARCHPROFILE_EYECOLORS cascade constraints;
drop table SEARCHPROFILE_FAMILYSTATUSTYPES cascade constraints;
drop table SEARCHPROFILE_HAIRCOLORS cascade constraints;
drop table SEARCHPROFILE_HOBBYTYPES cascade constraints;
drop table SEARCHPROFILE_RELIGIONS cascade constraints;
drop table SUBDIVISION cascade constraints;
drop table USER cascade constraints;
drop table USERACCOUNT cascade constraints;
drop table USERPROFILE cascade constraints;
drop table USERPROFILE_LANGUAGES cascade constraints;
drop table VISIT cascade constraints;
drop table VOUCHER cascade constraints;
create table ABOUTME (ID number(19,0) not null, ILIKE varchar2(255 char), IDONTLIKE varchar2(255 char), LOOKINGFOR varchar2(255 char), primary key (ID));
create table ADDRESS (ID number(19,0) not null, ZIPCODE varchar2(255 char), STREET varchar2(255 char), HOUSENR varchar2(255 char), CITY varchar2(255 char), COUNTRY varchar2(255 char), primary key (ID));
create table APPEARANCE (ID number(19,0) not null, HEIGHT number(10,0), WEIGHT number(10,0), BODYTYPE varchar2(255 char), EYECOLOR varchar2(255 char), HAIRCOLOR varchar2(255 char), ETHNICITY varchar2(255 char), primary key (ID));
create table APPEARANCE_APPEARANCESTYLES (APPEARANCE_ID number(19,0) not null, APPEARANCESTYLE varchar2(255 char));
create table CITY (ID number(19,0) not null, NAME varchar2(255 char), LATITUDE float, LONGITUDE float, POPULATION number(10,0), SUBDIVISION_ID number(19,0), primary key (ID));
create table CONTACTEVENT (ID number(19,0) not null, TIMESTAMP timestamp, USERACCOUNT_ID number(19,0), CONTACTEVENTTYPE varchar2(255 char), primary key (ID));
create table CREDITCARDACCOUNT (ID number(19,0) not null, NUMBER varchar2(255 char), FIRSTNAME varchar2(255 char), LASTNAME varchar2(255 char), VERIFICATIONCODE number(5,0), VALIDTHRU timestamp, primary key (ID));
create table FAVORITE (ID number(19,0) not null, TIME_STAMP timestamp, OWNER number(19,0), TARGET number(19,0), primary key (ID));
create table GEOLOCATION (ID number(19,0) not null, ZIPCODE varchar2(255 char), CITY_ID number(19,0), COUNTRY varchar2(255 char), SUBDIVISION_ID number(19,0), CONTINENT varchar2(255 char), primary key (ID));
create table IMAGEENTRY (ID number(19,0) not null, PROFILEIMAGE number(1,0), VISIBLE number(1,0), CLIENTFILENAME varchar2(255 char), LASTMODIFIED timestamp, MEDIATYPE varchar2(255 char), HEIGHT number(10,0), WIDTH number(10,0), REPOSITORYID varchar2(255 char), USERPROFILE_ID number(19,0), idx number(10,0), primary key (ID));
create table LANDINGPAGEACTION (ID number(19,0) not null, TOKEN varchar2(255 char), ACTIONTYPE varchar2(255 char), USERACCOUNT_ID number(19,0), primary key (ID));
create table LIFESTYLE (ID number(19,0) not null, DRINKTYPE varchar2(255 char), SMOKETYPE varchar2(255 char), OCCUPATIONTYPE varchar2(255 char), PROFESSIONTYPE varchar2(255 char), HOMETYPE varchar2(255 char), LIVINGSITUATION varchar2(255 char), PLAYINSTRUMENT number(1,0), SPORTSACTIVITYTYPE varchar2(255 char), HOLIDAYPLANNINGTYPE varchar2(255 char), primary key (ID));
create table LIFESTYLE_FOODTYPES (LIFESTYLE_ID number(19,0) not null, FOODTYPE varchar2(255 char));
create table LIFESTYLE_HOBBYTYPES (LIFESTYLE_ID number(19,0) not null, HOBBYTYPE varchar2(255 char));
create table LIFESTYLE_HOLIDAYTYPES (LIFESTYLE_ID number(19,0) not null, HOLIDAYTYPE varchar2(255 char));
create table LIFESTYLE_KITCHENTYPES (LIFESTYLE_ID number(19,0) not null, KITCHENTYPE varchar2(255 char));
create table LIFESTYLE_MUSICTYPES (LIFESTYLE_ID number(19,0) not null, MUSICTYPE varchar2(255 char));
create table LIFESTYLE_PETTYPES (LIFESTYLE_ID number(19,0) not null, PETTYPE varchar2(255 char));
create table LIFESTYLE_SPORTTYPES (LIFESTYLE_ID number(19,0) not null, SPORTTYPE varchar2(255 char));
create table MEMBERSHIP (ID number(19,0) not null, ACCEPTEDTERMS number(1,0), STARTDATE timestamp, ENDDATE timestamp, DURATIONTYPE varchar2(255 char), STATUS varchar2(255 char), TYPE varchar2(255 char), PAID number(1,0), BILLSENT timestamp, AMOUNT float, PAYMENTCHANNEL number(19,0), USERACCOUNT_ID number(19,0), primary key (ID));
create table MESSAGE (ID number(19,0) not null, MESSAGETYPE varchar2(255 char), MESSAGESTATE_RECEIVER varchar2(255 char), MESSAGESTATE_SENDER varchar2(255 char), TIME_STAMP timestamp, RECEIVER number(19,0), SENDER number(19,0), SUBJECT varchar2(255 char), TEXT varchar2(255 char), primary key (ID));
create table PAYMENTCHANNEL (ID number(19,0) not null, USERACCOUNT_ID number(19,0), primary key (ID));
create table PAYPALACCOUNT (ID number(19,0) not null, NAME varchar2(255 char), PAYPALID varchar2(255 char), primary key (ID));
create table SEARCHPROFILE (ID number(19,0) not null, PARTNERTYPE varchar2(255 char), MINAGE number(10,0), MAXAGE number(10,0), GEOLOCATION number(19,0), PARTNERSHIPTYPE varchar2(255 char), MOTHERLANGUAGE varchar2(255 char), HOUSEHOLDTYPE varchar2(255 char), MAXDISTANCE varchar2(255 char), MINHEIGHTCM number(10,0), MAXHEIGHTCM number(10,0), SMOKETYPE varchar2(255 char), INCOMETYPE varchar2(255 char), OCCUPATIONTYPE varchar2(255 char), primary key (ID));
create table SEARCHPROFILE_APPEARANCESTYLES (SEARCHPROFILE_ID number(19,0) not null, APPEARANCESTYLE varchar2(255 char));
create table SEARCHPROFILE_BODYTYPES (SEARCHPROFILE_ID number(19,0) not null, BODYTYPE varchar2(255 char));
create table SEARCHPROFILE_EDUCATIONTYPES (SEARCHPROFILE_ID number(19,0) not null, EDUCATIONTYPE varchar2(255 char));
create table SEARCHPROFILE_ETHNICITIES (SEARCHPROFILE_ID number(19,0) not null, ETHNICITY varchar2(255 char));
create table SEARCHPROFILE_EYECOLORS (SEARCHPROFILE_ID number(19,0) not null, EYECOLOR varchar2(255 char));
create table SEARCHPROFILE_FAMILYSTATUSTYPES (SEARCHPROFILE_ID number(19,0) not null, FAMILYSTATUSTYPE varchar2(255 char));
create table SEARCHPROFILE_HAIRCOLORS (SEARCHPROFILE_ID number(19,0) not null, HAIRCOLOR varchar2(255 char));
create table SEARCHPROFILE_HOBBYTYPES (SEARCHPROFILE_ID number(19,0) not null, HOBBYTYPE varchar2(255 char));
create table SEARCHPROFILE_RELIGIONS (SEARCHPROFILE_ID number(19,0) not null, RELIGION varchar2(255 char));
create table SUBDIVISION (ID number(19,0) not null, CODE varchar2(255 char), NAME varchar2(255 char), COUNTRYCODE varchar2(255 char), primary key (ID));
create table USER (ID number(19,0) not null, EMAIL varchar2(255 char), FIRSTNAME varchar2(255 char), LASTNAME varchar2(255 char), ADDRESS number(19,0), SEARCHPROFILE number(19,0), USERPROFILE number(19,0), primary key (ID));
create table USERACCOUNT (ID number(19,0) not null, PASSWORD varchar2(255 char), USERNAME varchar2(255 char), LASTLOGIN timestamp, ONLINE number(1,0), primary key (ID));
create table USERPROFILE (ID number(19,0) not null, PARTNERTYPE varchar2(255 char), BIRTHDATE timestamp, GEOLOCATION number(19,0), MOTHERLANGUAGE varchar2(255 char), RELIGION varchar2(255 char), FAMILYSTATUS varchar2(255 char), HOUSEHOLDTYPE varchar2(255 char), NUMBEROFKIDS varchar2(255 char), APPEARANCE number(19,0), EDUCATION varchar2(255 char), OCCUPATIONTYPE varchar2(255 char), INCOMETYPE varchar2(255 char), PROFESSION varchar2(255 char), LIFESTYLE number(19,0), MOTTO varchar2(255 char), primary key (ID));
create table USERPROFILE_LANGUAGES (USERPROFILE_ID number(19,0) not null, LANGUAGE varchar2(255 char));
create table VISIT (ID number(19,0) not null, TIME_STAMP timestamp, VISITEDUSER number(19,0), VISITOR number(19,0), primary key (ID));
create table VOUCHER (ID number(19,0) not null, CODE varchar2(255 char), GENERATEDDATE timestamp, ENCASHEDDATE timestamp, VALIDTHRU timestamp, primary key (ID));
alter table APPEARANCE_APPEARANCESTYLES add constraint FKE50768C16376BDD foreign key (APPEARANCE_ID) references APPEARANCE;
alter table CITY add constraint FK1F916BBA379CBA foreign key (SUBDIVISION_ID) references SUBDIVISION;
alter table CONTACTEVENT add constraint FKD69FCA7A90690217 foreign key (USERACCOUNT_ID) references USERACCOUNT;
alter table CREDITCARDACCOUNT add constraint FK16BD8C644FBB85B foreign key (ID) references PAYMENTCHANNEL;
alter table FAVORITE add constraint FK6D47B99CB424583F foreign key (TARGET) references USER;
alter table FAVORITE add constraint FK6D47B99CEEF9D961 foreign key (OWNER) references USER;
alter table GEOLOCATION add constraint FK844CE1E6BA379CBA foreign key (SUBDIVISION_ID) references SUBDIVISION;
alter table GEOLOCATION add constraint FK844CE1E66657EBBA foreign key (CITY_ID) references CITY;
alter table IMAGEENTRY add constraint FKC73CEBF7B24D0097 foreign key (USERPROFILE_ID) references USERPROFILE;
alter table LANDINGPAGEACTION add constraint FKBFBD62BC90690217 foreign key (USERACCOUNT_ID) references USERACCOUNT;
alter table LIFESTYLE_FOODTYPES add constraint FK981D8711D4687477 foreign key (LIFESTYLE_ID) references LIFESTYLE;
alter table LIFESTYLE_HOBBYTYPES add constraint FKAC308451D4687477 foreign key (LIFESTYLE_ID) references LIFESTYLE;
alter table LIFESTYLE_HOLIDAYTYPES add constraint FK8890870BD4687477 foreign key (LIFESTYLE_ID) references LIFESTYLE;
alter table LIFESTYLE_KITCHENTYPES add constraint FKAB52873FD4687477 foreign key (LIFESTYLE_ID) references LIFESTYLE;
alter table LIFESTYLE_MUSICTYPES add constraint FK1DEF4FDED4687477 foreign key (LIFESTYLE_ID) references LIFESTYLE;
alter table LIFESTYLE_PETTYPES add constraint FKCA10EFA4D4687477 foreign key (LIFESTYLE_ID) references LIFESTYLE;
alter table LIFESTYLE_SPORTTYPES add constraint FK4BE78FEFD4687477 foreign key (LIFESTYLE_ID) references LIFESTYLE;
alter table MEMBERSHIP add constraint FKCD0773D690690217 foreign key (USERACCOUNT_ID) references USERACCOUNT;
alter table MEMBERSHIP add constraint FKCD0773D69275C37D foreign key (PAYMENTCHANNEL) references PAYMENTCHANNEL;
alter table MESSAGE add constraint FK63B68BE7B2A600E3 foreign key (SENDER) references USER;
alter table MESSAGE add constraint FK63B68BE7B871D09D foreign key (RECEIVER) references USER;
alter table PAYMENTCHANNEL add constraint FKB7EFC3D90690217 foreign key (USERACCOUNT_ID) references USERACCOUNT;
alter table PAYPALACCOUNT add constraint FKF85B1BBA4FBB85B foreign key (ID) references PAYMENTCHANNEL;
alter table SEARCHPROFILE add constraint FK928C0EE16E1B8FE9 foreign key (GEOLOCATION) references GEOLOCATION;
alter table SEARCHPROFILE_APPEARANCESTYLES add constraint FK1B112BE4D4CB277 foreign key (SEARCHPROFILE_ID) references SEARCHPROFILE;
alter table SEARCHPROFILE_BODYTYPES add constraint FKCB868819D4CB277 foreign key (SEARCHPROFILE_ID) references SEARCHPROFILE;
alter table SEARCHPROFILE_EDUCATIONTYPES add constraint FK261FEEFD4CB277 foreign key (SEARCHPROFILE_ID) references SEARCHPROFILE;
alter table SEARCHPROFILE_ETHNICITIES add constraint FKF6BBE8DFD4CB277 foreign key (SEARCHPROFILE_ID) references SEARCHPROFILE;
alter table SEARCHPROFILE_EYECOLORS add constraint FKA62ED2E3D4CB277 foreign key (SEARCHPROFILE_ID) references SEARCHPROFILE;
alter table SEARCHPROFILE_FAMILYSTATUSTYPES add constraint FK19888FE5D4CB277 foreign key (SEARCHPROFILE_ID) references SEARCHPROFILE;
alter table SEARCHPROFILE_HAIRCOLORS add constraint FKBACE57F0D4CB277 foreign key (SEARCHPROFILE_ID) references SEARCHPROFILE;
alter table SEARCHPROFILE_HOBBYTYPES add constraint FKD6D77A05D4CB277 foreign key (SEARCHPROFILE_ID) references SEARCHPROFILE;
alter table SEARCHPROFILE_RELIGIONS add constraint FK8C278D64D4CB277 foreign key (SEARCHPROFILE_ID) references SEARCHPROFILE;
alter table USER add constraint FK27E3CBB636CE99 foreign key (USERPROFILE) references USERPROFILE;
alter table USER add constraint FK27E3CB20D2E25 foreign key (ADDRESS) references ADDRESS;
alter table USER add constraint FK27E3CB1DBE1A5F foreign key (SEARCHPROFILE) references SEARCHPROFILE;
alter table USERPROFILE add constraint FKF8AB675E272B4347 foreign key (LIFESTYLE) references LIFESTYLE;
alter table USERPROFILE add constraint FKF8AB675E6E1B8FE9 foreign key (GEOLOCATION) references GEOLOCATION;
alter table USERPROFILE add constraint FKF8AB675EF2217D6B foreign key (APPEARANCE) references APPEARANCE;
alter table USERPROFILE_LANGUAGES add constraint FKB6A92C5AB24D0097 foreign key (USERPROFILE_ID) references USERPROFILE;
alter table VISIT add constraint FK4DE552B4781B1C foreign key (VISITOR) references USER;
alter table VISIT add constraint FK4DE552B9CAD60A3 foreign key (VISITEDUSER) references USER;
alter table VOUCHER add constraint FK50F41A8E4FBB85B foreign key (ID) references PAYMENTCHANNEL;
