/* content copied from SchemaGenerator generated file */
drop table ABOUTME if exists;
drop table ADDRESS if exists;
drop table APPEARANCE if exists;
drop table APPEARANCE_APPEARANCESTYLES if exists;
drop table CITY if exists;
drop table CONTACTEVENT if exists;
drop table CREDITCARDACCOUNT if exists;
drop table FAVORITE if exists;
drop table GEOLOCATION if exists;
drop table IMAGEENTRY if exists;
drop table LIFESTYLE if exists;
drop table LIFESTYLE_FOODTYPES if exists;
drop table LIFESTYLE_HOBBYTYPES if exists;
drop table LIFESTYLE_HOLIDAYTYPES if exists;
drop table LIFESTYLE_KITCHENTYPES if exists;
drop table LIFESTYLE_MUSICTYPES if exists;
drop table LIFESTYLE_PETTYPES if exists;
drop table LIFESTYLE_SPORTTYPES if exists;
drop table MEMBERSHIP if exists;
drop table MESSAGE if exists;
drop table PAYMENTCHANNEL if exists;
drop table PAYPALACCOUNT if exists;
drop table SEARCHPROFILE if exists;
drop table SEARCHPROFILE_APPEARANCESTYLES if exists;
drop table SEARCHPROFILE_BODYTYPES if exists;
drop table SEARCHPROFILE_EDUCATIONTYPES if exists;
drop table SEARCHPROFILE_ETHNICITIES if exists;
drop table SEARCHPROFILE_EYECOLORS if exists;
drop table SEARCHPROFILE_FAMILYSTATUSTYPES if exists;
drop table SEARCHPROFILE_HAIRCOLORS if exists;
drop table SEARCHPROFILE_HOBBYTYPES if exists;
drop table SEARCHPROFILE_RELIGIONS if exists;
drop table SUBDIVISION if exists;
drop table USERS if exists;
drop table USERACCOUNT if exists;
drop table USERPROFILE if exists;
drop table USERPROFILE_LANGUAGES if exists;
drop table VISIT if exists;
drop table VOUCHER if exists;
create table ABOUTME (ID bigint not null, IDOLIKE varchar(255), IDONTLIKE varchar(255), LOOKINGFOR varchar(255), primary key (ID));
create table ADDRESS (ID bigint not null, ZIPCODE varchar(255), STREET varchar(255), HOUSENR varchar(255), CITY varchar(255), COUNTRY varchar(255), primary key (ID));
create table APPEARANCE (ID bigint not null, HEIGHT integer, WEIGHT integer, BODYTYPE varchar(255), EYECOLOR varchar(255), HAIRCOLOR varchar(255), ETHNICITY varchar(255), primary key (ID));
create table APPEARANCE_APPEARANCESTYLES (APPEARANCE_ID bigint not null, APPEARANCESTYLE varchar(255));
create table CITY (ID bigint not null, NAME varchar(255), LATITUDE float, LONGITUDE float, POPULATION integer, SUBDIVISION_ID bigint, primary key (ID));
create table CONTACTEVENT (ID bigint not null, TIMESTAMP timestamp, USERACCOUNT_ID bigint, CONTACTEVENTTYPE varchar(255), primary key (ID));
create table CREDITCARDACCOUNT (ID bigint not null, NUMBER varchar(255), FIRSTNAME varchar(255), LASTNAME varchar(255), VERIFICATIONCODE smallint, VALIDTHRU timestamp, primary key (ID));
create table FAVORITE (ID bigint not null, TIME_STAMP timestamp, OWNER bigint, TARGET bigint, primary key (ID));
create table GEOLOCATION (ID bigint not null, ZIPCODE varchar(255), CITY_ID bigint, COUNTRY varchar(255), SUBDIVISION_ID bigint, CONTINENT varchar(255), primary key (ID));
create table IMAGEENTRY (ID bigint not null, PROFILEIMAGE bit, VISIBLE bit, CLIENTFILENAME varchar(255), LASTMODIFIED timestamp, MEDIATYPE varchar(255), HEIGHT integer, WIDTH integer, REPOSITORYID varchar(255), USERPROFILE_ID bigint, idx integer, primary key (ID));
create table LIFESTYLE (ID bigint not null, DRINKTYPE varchar(255), SMOKETYPE varchar(255), OCCUPATIONTYPE varchar(255), PROFESSIONTYPE varchar(255), HOMETYPE varchar(255), LIVINGSITUATION varchar(255), PLAYINSTRUMENT bit, SPORTSACTIVITYTYPE varchar(255), HOLIDAYPLANNINGTYPE varchar(255), primary key (ID));
create table LIFESTYLE_FOODTYPES (LIFESTYLE_ID bigint not null, FOODTYPE varchar(255));
create table LIFESTYLE_HOBBYTYPES (LIFESTYLE_ID bigint not null, HOBBYTYPE varchar(255));
create table LIFESTYLE_HOLIDAYTYPES (LIFESTYLE_ID bigint not null, HOLIDAYTYPE varchar(255));
create table LIFESTYLE_KITCHENTYPES (LIFESTYLE_ID bigint not null, KITCHENTYPE varchar(255));
create table LIFESTYLE_MUSICTYPES (LIFESTYLE_ID bigint not null, MUSICTYPE varchar(255));
create table LIFESTYLE_PETTYPES (LIFESTYLE_ID bigint not null, PETTYPE varchar(255));
create table LIFESTYLE_SPORTTYPES (LIFESTYLE_ID bigint not null, SPORTTYPE varchar(255));
create table MEMBERSHIP (ID bigint not null, ACCEPTEDTERMS bit, STARTDATE timestamp, ENDDATE timestamp, DURATIONTYPE varchar(255), STATUS varchar(255), TYPE varchar(255), PAID bit, BILLSENT timestamp, AMOUNT float, PAYMENTCHANNEL bigint, USERACCOUNT_ID bigint, primary key (ID));
create table MESSAGE (ID bigint not null, MESSAGETYPE varchar(255), MESSAGESTATE_RECEIVER varchar(255), MESSAGESTATE_SENDER varchar(255), TIME_STAMP timestamp, RECEIVER bigint, SENDER bigint, SUBJECT varchar(255), TEXT varchar(255), primary key (ID));
create table PAYMENTCHANNEL (ID bigint not null, USERACCOUNT_ID bigint, primary key (ID));
create table PAYPALACCOUNT (ID bigint not null, NAME varchar(255), PAYPALID varchar(255), primary key (ID));
create table SEARCHPROFILE (ID bigint not null, PARTNERTYPE varchar(255), MINAGE integer, MAXAGE integer, GEOLOCATION bigint, PARTNERSHIPTYPE varchar(255), MOTHERLANGUAGE varchar(255), HOUSEHOLDTYPE varchar(255), MAXDISTANCE varchar(255), MINHEIGHTCM integer, MAXHEIGHTCM integer, SMOKETYPE varchar(255), INCOMETYPE varchar(255), OCCUPATIONTYPE varchar(255), primary key (ID));
create table SEARCHPROFILE_APPEARANCESTYLES (SEARCHPROFILE_ID bigint not null, APPEARANCESTYLE varchar(255));
create table SEARCHPROFILE_BODYTYPES (SEARCHPROFILE_ID bigint not null, BODYTYPE varchar(255));
create table SEARCHPROFILE_EDUCATIONTYPES (SEARCHPROFILE_ID bigint not null, EDUCATIONTYPE varchar(255));
create table SEARCHPROFILE_ETHNICITIES (SEARCHPROFILE_ID bigint not null, ETHNICITY varchar(255));
create table SEARCHPROFILE_EYECOLORS (SEARCHPROFILE_ID bigint not null, EYECOLOR varchar(255));
create table SEARCHPROFILE_FAMILYSTATUSTYPES (SEARCHPROFILE_ID bigint not null, FAMILYSTATUSTYPE varchar(255));
create table SEARCHPROFILE_HAIRCOLORS (SEARCHPROFILE_ID bigint not null, HAIRCOLOR varchar(255));
create table SEARCHPROFILE_HOBBYTYPES (SEARCHPROFILE_ID bigint not null, HOBBYTYPE varchar(255));
create table SEARCHPROFILE_RELIGIONS (SEARCHPROFILE_ID bigint not null, RELIGION varchar(255));
create table SUBDIVISION (ID bigint not null, CODE varchar(255), NAME varchar(255), COUNTRYCODE varchar(255), primary key (ID));
create table USERS (ID bigint not null, EMAIL varchar(255), FIRSTNAME varchar(255), LASTNAME varchar(255), ADDRESS bigint, SEARCHPROFILE bigint, USERPROFILE bigint, primary key (ID));
create table USERACCOUNT (ID bigint not null, PASSWORD varchar(255), USERNAME varchar(255), LASTLOGIN timestamp, ONLINE bit, primary key (ID));
create table USERPROFILE (ID bigint not null, PARTNERTYPE varchar(255), BIRTHDATE timestamp, GEOLOCATION bigint, MOTHERLANGUAGE varchar(255), RELIGION varchar(255), FAMILYSTATUS varchar(255), HOUSEHOLDTYPE varchar(255), NUMBEROFKIDS varchar(255), APPEARANCE bigint, EDUCATION varchar(255), OCCUPATIONTYPE varchar(255), INCOMETYPE varchar(255), PROFESSION varchar(255), LIFESTYLE bigint, MOTTO varchar(255), primary key (ID));
create table USERPROFILE_LANGUAGES (USERPROFILE_ID bigint not null, LANGUAGE varchar(255));
create table VISIT (ID bigint not null, TIME_STAMP timestamp, VISITEDUSER bigint, VISITOR bigint, primary key (ID));
create table VOUCHER (ID bigint not null, CODE varchar(255), GENERATEDDATE timestamp, ENCASHEDDATE timestamp, VALIDTHRU timestamp, primary key (ID));
alter table APPEARANCE_APPEARANCESTYLES add constraint FKE50768C16376BDD foreign key (APPEARANCE_ID) references APPEARANCE;
alter table CITY add constraint FK1F916BBA379CBA foreign key (SUBDIVISION_ID) references SUBDIVISION;
alter table CONTACTEVENT add constraint FKD69FCA7A90690217 foreign key (USERACCOUNT_ID) references USERACCOUNT;
alter table CREDITCARDACCOUNT add constraint FK16BD8C644FBB85B foreign key (ID) references PAYMENTCHANNEL;
alter table FAVORITE add constraint FK6D47B99CB424583F foreign key (TARGET) references USERS;
alter table FAVORITE add constraint FK6D47B99CEEF9D961 foreign key (OWNER) references USERS;
alter table GEOLOCATION add constraint FK844CE1E6BA379CBA foreign key (SUBDIVISION_ID) references SUBDIVISION;
alter table GEOLOCATION add constraint FK844CE1E66657EBBA foreign key (CITY_ID) references CITY;
alter table IMAGEENTRY add constraint FKC73CEBF7B24D0097 foreign key (USERPROFILE_ID) references USERPROFILE;
alter table LIFESTYLE_FOODTYPES add constraint FK981D8711D4687477 foreign key (LIFESTYLE_ID) references LIFESTYLE;
alter table LIFESTYLE_HOBBYTYPES add constraint FKAC308451D4687477 foreign key (LIFESTYLE_ID) references LIFESTYLE;
alter table LIFESTYLE_HOLIDAYTYPES add constraint FK8890870BD4687477 foreign key (LIFESTYLE_ID) references LIFESTYLE;
alter table LIFESTYLE_KITCHENTYPES add constraint FKAB52873FD4687477 foreign key (LIFESTYLE_ID) references LIFESTYLE;
alter table LIFESTYLE_MUSICTYPES add constraint FK1DEF4FDED4687477 foreign key (LIFESTYLE_ID) references LIFESTYLE;
alter table LIFESTYLE_PETTYPES add constraint FKCA10EFA4D4687477 foreign key (LIFESTYLE_ID) references LIFESTYLE;
alter table LIFESTYLE_SPORTTYPES add constraint FK4BE78FEFD4687477 foreign key (LIFESTYLE_ID) references LIFESTYLE;
alter table MEMBERSHIP add constraint FKCD0773D690690217 foreign key (USERACCOUNT_ID) references USERACCOUNT;
alter table MEMBERSHIP add constraint FKCD0773D69275C37D foreign key (PAYMENTCHANNEL) references PAYMENTCHANNEL;
alter table MESSAGE add constraint FK63B68BE7B2A600E3 foreign key (SENDER) references USERS;
alter table MESSAGE add constraint FK63B68BE7B871D09D foreign key (RECEIVER) references USERS;
alter table PAYMENTCHANNEL add constraint FKB7EFC3D90690217 foreign key (USERACCOUNT_ID) references USERACCOUNT;
alter table PAYPALACCOUNT add constraint FKF85B1BBA4FBB85B foreign key (ID) references PAYMENTCHANNEL;
alter table SEARCHPROFILE add constraint FK928C0EE16E1B8FE9 foreign key (GEOLOCATION) references GEOLOCATION;
alter table SEARCHPROFILE_APPEARANCESTYLES add constraint FK1B112BE4D4CB277 foreign key (SEARCHPROFILE_ID) references SEARCHPROFILE;
alter table SEARCHPROFILE_BODYTYPES add constraint FKCB868819D4CB277 foreign key (SEARCHPROFILE_ID) references SEARCHPROFILE;
alter table SEARCHPROFILE_EDUCATIONTYPES add constraint FK261FEEFD4CB277 foreign key (SEARCHPROFILE_ID) references SEARCHPROFILE;
alter table SEARCHPROFILE_ETHNICITIES add constraint FKF6BBE8DFD4CB277 foreign key (SEARCHPROFILE_ID) references SEARCHPROFILE;
alter table SEARCHPROFILE_EYECOLORS add constraint FKA62ED2E3D4CB277 foreign key (SEARCHPROFILE_ID) references SEARCHPROFILE;
alter table SEARCHPROFILE_FAMILYSTATUSTYPES add constraint FK19888FE5D4CB277 foreign key (SEARCHPROFILE_ID) references SEARCHPROFILE;
alter table SEARCHPROFILE_HAIRCOLORS add constraint FKBACE57F0D4CB277 foreign key (SEARCHPROFILE_ID) references SEARCHPROFILE;
alter table SEARCHPROFILE_HOBBYTYPES add constraint FKD6D77A05D4CB277 foreign key (SEARCHPROFILE_ID) references SEARCHPROFILE;
alter table SEARCHPROFILE_RELIGIONS add constraint FK8C278D64D4CB277 foreign key (SEARCHPROFILE_ID) references SEARCHPROFILE;
alter table USERS add constraint FK27E3CBB636CE99 foreign key (USERPROFILE) references USERPROFILE;
alter table USERS add constraint FK27E3CB20D2E25 foreign key (ADDRESS) references ADDRESS;
alter table USERS add constraint FK27E3CB1DBE1A5F foreign key (SEARCHPROFILE) references SEARCHPROFILE;
alter table USERPROFILE add constraint FKF8AB675E272B4347 foreign key (LIFESTYLE) references LIFESTYLE;
alter table USERPROFILE add constraint FKF8AB675E6E1B8FE9 foreign key (GEOLOCATION) references GEOLOCATION;
alter table USERPROFILE add constraint FKF8AB675EF2217D6B foreign key (APPEARANCE) references APPEARANCE;
alter table USERPROFILE_LANGUAGES add constraint FKB6A92C5AB24D0097 foreign key (USERPROFILE_ID) references USERPROFILE;
alter table VISIT add constraint FK4DE552B4781B1C foreign key (VISITOR) references USERS;
alter table VISIT add constraint FK4DE552B9CAD60A3 foreign key (VISITEDUSER) references USERS;
alter table VOUCHER add constraint FK50F41A8E4FBB85B foreign key (ID) references PAYMENTCHANNEL;
