/* content copied from SchemaGenerator generated file */
drop table if exists ABOUTME;
drop table if exists ADDRESS;
drop table if exists APPEARANCE;
drop table if exists APPEARANCE_APPEARANCESTYLES;
drop table if exists CITY;
drop table if exists CONTACTEVENT;
drop table if exists CREDITCARDACCOUNT;
drop table if exists FAVORITE;
drop table if exists GEOLOCATION;
drop table if exists IMAGEENTRY;
drop table if exists LANDINGPAGEACTION;
drop table if exists LIFESTYLE;
drop table if exists LIFESTYLE_FOODTYPES;
drop table if exists LIFESTYLE_HOBBYTYPES;
drop table if exists LIFESTYLE_HOLIDAYTYPES;
drop table if exists LIFESTYLE_KITCHENTYPES;
drop table if exists LIFESTYLE_MUSICTYPES;
drop table if exists LIFESTYLE_PETTYPES;
drop table if exists LIFESTYLE_SPORTTYPES;
drop table if exists MEMBERSHIP;
drop table if exists MESSAGE;
drop table if exists PAYMENTCHANNEL;
drop table if exists PAYPALACCOUNT;
drop table if exists SEARCHPROFILE;
drop table if exists SEARCHPROFILE_APPEARANCESTYLES;
drop table if exists SEARCHPROFILE_BODYTYPES;
drop table if exists SEARCHPROFILE_EDUCATIONTYPES;
drop table if exists SEARCHPROFILE_ETHNICITIES;
drop table if exists SEARCHPROFILE_EYECOLORS;
drop table if exists SEARCHPROFILE_FAMILYSTATUSTYPES;
drop table if exists SEARCHPROFILE_HAIRCOLORS;
drop table if exists SEARCHPROFILE_HOBBYTYPES;
drop table if exists SEARCHPROFILE_RELIGIONS;
drop table if exists SUBDIVISION;
drop table if exists USERS;
drop table if exists USERACCOUNT;
drop table if exists USERPROFILE;
drop table if exists USERPROFILE_LANGUAGES;
drop table if exists VISIT;
drop table if exists VOUCHER;
create table ABOUTME (ID int8 not null, IDOLIKE varchar(255), IDONTLIKE varchar(255), LOOKINGFOR varchar(255), primary key (ID));
create table ADDRESS (ID int8 not null, ZIPCODE varchar(255), STREET varchar(255), HOUSENR varchar(255), CITY varchar(255), COUNTRY varchar(255), primary key (ID));
create table APPEARANCE (ID int8 not null, HEIGHT int4, WEIGHT int4, BODYTYPE varchar(255), EYECOLOR varchar(255), HAIRCOLOR varchar(255), ETHNICITY varchar(255), primary key (ID));
create table APPEARANCE_APPEARANCESTYLES (APPEARANCE_ID int8 not null, APPEARANCESTYLE varchar(255));
create table CITY (ID int8 not null, NAME varchar(255), LATITUDE float4, LONGITUDE float4, POPULATION int4, SUBDIVISION_ID int8, primary key (ID));
create table CONTACTEVENT (ID int8 not null, TIMESTAMP timestamp, USERACCOUNT_ID int8, CONTACTEVENTTYPE varchar(255), primary key (ID));
create table CREDITCARDACCOUNT (ID int8 not null, NUMBER varchar(255), FIRSTNAME varchar(255), LASTNAME varchar(255), VERIFICATIONCODE int2, VALIDTHRU timestamp, primary key (ID));
create table FAVORITE (ID int8 not null, TIME_STAMP timestamp, OWNER int8, TARGET int8, primary key (ID));
create table GEOLOCATION (ID int8 not null, ZIPCODE varchar(255), CITY_ID int8, COUNTRY varchar(255), SUBDIVISION_ID int8, CONTINENT varchar(255), primary key (ID));
create table IMAGEENTRY (ID int8 not null, PROFILEIMAGE bool, VISIBLE bool, CLIENTFILENAME varchar(255), LASTMODIFIED timestamp, MEDIATYPE varchar(255), HEIGHT int4, WIDTH int4, REPOSITORYID varchar(255), USERPROFILE_ID int8, idx int4, primary key (ID));
create table LIFESTYLE (ID int8 not null, DRINKTYPE varchar(255), SMOKETYPE varchar(255), OCCUPATIONTYPE varchar(255), PROFESSIONTYPE varchar(255), HOMETYPE varchar(255), LIVINGSITUATION varchar(255), PLAYINSTRUMENT bool, SPORTSACTIVITYTYPE varchar(255), HOLIDAYPLANNINGTYPE varchar(255), primary key (ID));
create table LIFESTYLE_FOODTYPES (LIFESTYLE_ID int8 not null, FOODTYPE varchar(255));
create table LIFESTYLE_HOBBYTYPES (LIFESTYLE_ID int8 not null, HOBBYTYPE varchar(255));
create table LIFESTYLE_HOLIDAYTYPES (LIFESTYLE_ID int8 not null, HOLIDAYTYPE varchar(255));
create table LIFESTYLE_KITCHENTYPES (LIFESTYLE_ID int8 not null, KITCHENTYPE varchar(255));
create table LIFESTYLE_MUSICTYPES (LIFESTYLE_ID int8 not null, MUSICTYPE varchar(255));
create table LIFESTYLE_PETTYPES (LIFESTYLE_ID int8 not null, PETTYPE varchar(255));
create table LIFESTYLE_SPORTTYPES (LIFESTYLE_ID int8 not null, SPORTTYPE varchar(255));
create table MEMBERSHIP (ID int8 not null, ACCEPTEDTERMS bool, STARTDATE timestamp, ENDDATE timestamp, DURATIONTYPE varchar(255), STATUS varchar(255), TYPE varchar(255), PAID bool, BILLSENT timestamp, AMOUNT float4, PAYMENTCHANNEL int8, USERACCOUNT_ID int8, primary key (ID));
create table MESSAGE (ID int8 not null, MESSAGETYPE varchar(255), MESSAGESTATE_RECEIVER varchar(255), MESSAGESTATE_SENDER varchar(255), TIME_STAMP timestamp, RECEIVER int8, SENDER int8, SUBJECT varchar(255), TEXT varchar(255), primary key (ID));
create table PAYMENTCHANNEL (ID int8 not null, USERACCOUNT_ID int8, primary key (ID));
create table PAYPALACCOUNT (ID int8 not null, NAME varchar(255), PAYPALID varchar(255), primary key (ID));
create table SEARCHPROFILE (ID int8 not null, PARTNERTYPE varchar(255), MINAGE int4, MAXAGE int4, GEOLOCATION int8, PARTNERSHIPTYPE varchar(255), MOTHERLANGUAGE varchar(255), HOUSEHOLDTYPE varchar(255), MAXDISTANCE varchar(255), MINHEIGHTCM int4, MAXHEIGHTCM int4, SMOKETYPE varchar(255), INCOMETYPE varchar(255), OCCUPATIONTYPE varchar(255), primary key (ID));
create table SEARCHPROFILE_APPEARANCESTYLES (SEARCHPROFILE_ID int8 not null, APPEARANCESTYLE varchar(255));
create table SEARCHPROFILE_BODYTYPES (SEARCHPROFILE_ID int8 not null, BODYTYPE varchar(255));
create table SEARCHPROFILE_EDUCATIONTYPES (SEARCHPROFILE_ID int8 not null, EDUCATIONTYPE varchar(255));
create table SEARCHPROFILE_ETHNICITIES (SEARCHPROFILE_ID int8 not null, ETHNICITY varchar(255));
create table SEARCHPROFILE_EYECOLORS (SEARCHPROFILE_ID int8 not null, EYECOLOR varchar(255));
create table SEARCHPROFILE_FAMILYSTATUSTYPES (SEARCHPROFILE_ID int8 not null, FAMILYSTATUSTYPE varchar(255));
create table SEARCHPROFILE_HAIRCOLORS (SEARCHPROFILE_ID int8 not null, HAIRCOLOR varchar(255));
create table SEARCHPROFILE_HOBBYTYPES (SEARCHPROFILE_ID int8 not null, HOBBYTYPE varchar(255));
create table SEARCHPROFILE_RELIGIONS (SEARCHPROFILE_ID int8 not null, RELIGION varchar(255));
create table SUBDIVISION (ID int8 not null, CODE varchar(255), NAME varchar(255), COUNTRYCODE varchar(255), primary key (ID));
create table USERS (ID int8 not null, EMAIL varchar(255), FIRSTNAME varchar(255), LASTNAME varchar(255), ADDRESS int8, SEARCHPROFILE int8, USERPROFILE int8, primary key (ID));
create table USERACCOUNT (ID int8 not null, PASSWORD varchar(255), USERNAME varchar(255), LASTLOGIN timestamp, ONLINE bool, primary key (ID));
create table USERPROFILE (ID int8 not null, PARTNERTYPE varchar(255), BIRTHDATE timestamp, GEOLOCATION int8, MOTHERLANGUAGE varchar(255), RELIGION varchar(255), FAMILYSTATUS varchar(255), HOUSEHOLDTYPE varchar(255), NUMBEROFKIDS varchar(255), APPEARANCE int8, EDUCATION varchar(255), OCCUPATIONTYPE varchar(255), INCOMETYPE varchar(255), PROFESSION varchar(255), LIFESTYLE int8, MOTTO varchar(255), primary key (ID));
create table USERPROFILE_LANGUAGES (USERPROFILE_ID int8 not null, LANGUAGE varchar(255));
create table VISIT (ID int8 not null, TIME_STAMP timestamp, VISITEDUSER int8, VISITOR int8, primary key (ID));
create table VOUCHER (ID int8 not null, CODE varchar(255), GENERATEDDATE timestamp, ENCASHEDDATE timestamp, VALIDTHRU timestamp, primary key (ID));
alter table APPEARANCE_APPEARANCESTYLES add constraint FKE50768C16376BDD foreign key (APPEARANCE_ID) references APPEARANCE;
alter table CITY add constraint FK1F916BBA379CBA foreign key (SUBDIVISION_ID) references SUBDIVISION;
alter table CONTACTEVENT add constraint FKD69FCA7A90690217 foreign key (USERACCOUNT_ID) references USERACCOUNT;
alter table CREDITCARDACCOUNT add constraint FK16BD8C644FBB85B foreign key (ID) references PAYMENTCHANNEL;
alter table FAVORITE add constraint FK6D47B99CB424583F foreign key (TARGET) references USERS;
alter table FAVORITE add constraint FK6D47B99CEEF9D961 foreign key (OWNER) references USERS;
alter table GEOLOCATION add constraint FK844CE1E6BA379CBA foreign key (SUBDIVISION_ID) references SUBDIVISION;
alter table GEOLOCATION add constraint FK844CE1E66657EBBA foreign key (CITY_ID) references CITY;
alter table IMAGEENTRY add constraint FKC73CEBF7B24D0097 foreign key (USERPROFILE_ID) references USERPROFILE;
alter table LIFESTYLE_FOODTYPES add constraint FK981D8711D4687477 foreign key (LIFESTYLE_ID) references LIFESTYLE;
alter table LIFESTYLE_HOBBYTYPES add constraint FKAC308451D4687477 foreign key (LIFESTYLE_ID) references LIFESTYLE;
alter table LIFESTYLE_HOLIDAYTYPES add constraint FK8890870BD4687477 foreign key (LIFESTYLE_ID) references LIFESTYLE;
alter table LIFESTYLE_KITCHENTYPES add constraint FKAB52873FD4687477 foreign key (LIFESTYLE_ID) references LIFESTYLE;
alter table LIFESTYLE_MUSICTYPES add constraint FK1DEF4FDED4687477 foreign key (LIFESTYLE_ID) references LIFESTYLE;
alter table LIFESTYLE_PETTYPES add constraint FKCA10EFA4D4687477 foreign key (LIFESTYLE_ID) references LIFESTYLE;
alter table LIFESTYLE_SPORTTYPES add constraint FK4BE78FEFD4687477 foreign key (LIFESTYLE_ID) references LIFESTYLE;
alter table MEMBERSHIP add constraint FKCD0773D690690217 foreign key (USERACCOUNT_ID) references USERACCOUNT;
alter table MEMBERSHIP add constraint FKCD0773D69275C37D foreign key (PAYMENTCHANNEL) references PAYMENTCHANNEL;
alter table MESSAGE add constraint FK63B68BE7B2A600E3 foreign key (SENDER) references USERS;
alter table MESSAGE add constraint FK63B68BE7B871D09D foreign key (RECEIVER) references USERS;
alter table PAYMENTCHANNEL add constraint FKB7EFC3D90690217 foreign key (USERACCOUNT_ID) references USERACCOUNT;
alter table PAYPALACCOUNT add constraint FKF85B1BBA4FBB85B foreign key (ID) references PAYMENTCHANNEL;
alter table SEARCHPROFILE add constraint FK928C0EE16E1B8FE9 foreign key (GEOLOCATION) references GEOLOCATION;
alter table SEARCHPROFILE_APPEARANCESTYLES add constraint FK1B112BE4D4CB277 foreign key (SEARCHPROFILE_ID) references SEARCHPROFILE;
alter table SEARCHPROFILE_BODYTYPES add constraint FKCB868819D4CB277 foreign key (SEARCHPROFILE_ID) references SEARCHPROFILE;
alter table SEARCHPROFILE_EDUCATIONTYPES add constraint FK261FEEFD4CB277 foreign key (SEARCHPROFILE_ID) references SEARCHPROFILE;
alter table SEARCHPROFILE_ETHNICITIES add constraint FKF6BBE8DFD4CB277 foreign key (SEARCHPROFILE_ID) references SEARCHPROFILE;
alter table SEARCHPROFILE_EYECOLORS add constraint FKA62ED2E3D4CB277 foreign key (SEARCHPROFILE_ID) references SEARCHPROFILE;
alter table SEARCHPROFILE_FAMILYSTATUSTYPES add constraint FK19888FE5D4CB277 foreign key (SEARCHPROFILE_ID) references SEARCHPROFILE;
alter table SEARCHPROFILE_HAIRCOLORS add constraint FKBACE57F0D4CB277 foreign key (SEARCHPROFILE_ID) references SEARCHPROFILE;
alter table SEARCHPROFILE_HOBBYTYPES add constraint FKD6D77A05D4CB277 foreign key (SEARCHPROFILE_ID) references SEARCHPROFILE;
alter table SEARCHPROFILE_RELIGIONS add constraint FK8C278D64D4CB277 foreign key (SEARCHPROFILE_ID) references SEARCHPROFILE;
alter table USERS add constraint FK27E3CBB636CE99 foreign key (USERPROFILE) references USERPROFILE;
alter table USERS add constraint FK27E3CB20D2E25 foreign key (ADDRESS) references ADDRESS;
alter table USERS add constraint FK27E3CB1DBE1A5F foreign key (SEARCHPROFILE) references SEARCHPROFILE;
alter table USERPROFILE add constraint FKF8AB675E272B4347 foreign key (LIFESTYLE) references LIFESTYLE;
alter table USERPROFILE add constraint FKF8AB675E6E1B8FE9 foreign key (GEOLOCATION) references GEOLOCATION;
alter table USERPROFILE add constraint FKF8AB675EF2217D6B foreign key (APPEARANCE) references APPEARANCE;
alter table USERPROFILE_LANGUAGES add constraint FKB6A92C5AB24D0097 foreign key (USERPROFILE_ID) references USERPROFILE;
alter table VISIT add constraint FK4DE552B4781B1C foreign key (VISITOR) references USERS;
alter table VISIT add constraint FK4DE552B9CAD60A3 foreign key (VISITEDUSER) references USERS;
alter table VOUCHER add constraint FK50F41A8E4FBB85B foreign key (ID) references PAYMENTCHANNEL;
