update GEOAREA set MAXDISTANCE='UNITS_20' where MAXDISTANCE='KM20';
update GEOAREA set MAXDISTANCE='UNITS_50' where MAXDISTANCE='KM50';
update GEOAREA set MAXDISTANCE='UNITS_100' where MAXDISTANCE='KM100';
update GEOAREA set MAXDISTANCE='UNITS_250' where MAXDISTANCE='KM250';