update ADDRESS set VERSION_ID=0;
update APPEARANCE set VERSION_ID=0;
update BLOCKEDUSER set VERSION_ID=0;
update CONTACTEVENT set VERSION_ID=0;
update FAVORITE set VERSION_ID=0;
update GEOAREA set VERSION_ID=0;
update GEOLOCATION set VERSION_ID=0;
update IMAGEENTRY set VERSION_ID=0;
update LANDINGPAGEACTION set VERSION_ID=0;
update LIFESTYLE set VERSION_ID=0;
update MEMBERSHIP set VERSION_ID=0;
update MESSAGE set VERSION_ID=0;
update NOTIFICATIONSETTINGS set VERSION_ID=0;
update PAYMENTCHANNELS set VERSION_ID=0;
update PERSONALVALUES set VERSION_ID=0;
update PRODUCT set VERSION_ID=0;
update PROMOTION set VERSION_ID=0;
update SEARCHPROFILE set VERSION_ID=0;
update SUBDIVISION set VERSION_ID=0;
update TRANSACTION set VERSION_ID=0;
update USERS set VERSION_ID=0;
update USERACCOUNT set VERSION_ID=0;
update USERPROFILE set VERSION_ID=0;
update VISIT set VERSION_ID=0;

/* not in BANKACCOUNT sub-table but in PAYMENTCHANNELS */
/* not in CREDITCARDACCOUNT sub-table but in PAYMENTCHANNELS */
/* not in PAYONETRANSACTION sub-table but in TRANSACTION */
/* not in VOUCHER_PAYMENT sub-table but in PAYMENTCHANNELS */
/* not in WALLETACCOUNT sub-table but in PAYMENTCHANNELS */